ORG 00H
	LJMP MAIN
ORG 03H
	LJMP EXINT 
ORG 0BH
	ACALL TIMER
	RET
ORG 30H
MAIN:
        MOV A,#0
        MOV DPTR ,#400H
	MOV TMOD,#00010010B   ; TIMER 1 IN 16 BIT MODE AND TIMER 0 IN 8 BIT MODE
	MOV TH0,#-250
	MOV IE,#10000011B     ; ENABLING INTRUPT OF TIMER 0 AND EXT 0
	SETB TR0              
	CLR P2.0	      ; SETING PORT LOW IN START SO MOTOR ALWAYS IN REST CONDITION WHEN PROGRAM START
	H:
	SJMP H	
EXINT:
        ACALL DELAY           ; CALLING DELAY TO SAFELY INC A WITHOUT ANY ABNORMALITIES
        INC A
        CJNE A,#1,ONE         ; 50%
	MOV R1,#-125
	MOV R2,#-125
	SJMP L	
ONE:	CJNE A,#2,TWO         ; 75%
	MOV R1,#-175
	MOV R2,#-75
	SJMP L
	TWO:CJNE A,#3,THREE   ; 100%
	SETB P2.0
	SJMP L
	THREE:CJNE A,#4,F     ; 0%
	CLR P2.0
	MOV A,#0
	F:
	L:
	RETI
TIMER:                        ;TIMER INTRUPT SUBROUTINE FIRST 2 CJNE CHECKING MOTOR HAVE FULL SPEED OR STOP 
	CJNE A,#0,CH
	SJMP FF
	CH:CJNE A,#3,CH1
	SJMP FF
	CH1:JB P2.0,HI        ;LOADING REQUIRED VALUE OF LOW AND HIGH PAR OF WAVE IN TIMER 0
	MOV TH0,R2
	SETB P2.0
	RETI
	HI:
	MOV TH0,R1
	CLR P2.0
	FF:
	RETI
DELAY:                  ;GENERATING DELAY TO STOP UNREQUIRED INC OF A USING TIMER 1
MOV R4,#10
KK:MOV TH1,#3CH
MOV TL1,#0B0H
SETB TR1
JJ:JNB TF1,JJ
CLR TR1
CLR TF1
DJNZ R4,KK
RET
END